/*
 *  Macro to run the offline for all the detectors simultaneously
 *
 *  One needs to set up the Phase0 experiments, in this case s455
 *
 *  This macro takes the root files generated by the unpack_offline macro
 *  and processes the mapped data to get the next data levels (Cal and hit)
 *
 *  Author: Jose Luis <joseluis.rodriguez.sanchez@usc.es>
 *  @since May 4th, 2021
 *
 */

void cal_offline()
{
    TStopwatch timer;
    timer.Start();

    auto t = std::time(nullptr);
    auto tm = *std::localtime(&t);
    std::ostringstream oss;
    oss << std::put_time(&tm, "%Y%m%d_%H%M%S");

    // const Int_t nev = -1; // number of events to read, -1 - until CTRL+C
    const Int_t nev = -1; // Only nev events to read
    const Int_t fRunId = 1;

    // *********************************** //
    // PLEASE CHANGE THE EXPERIMENT NUMBER //
    // *********************************** //
    const Int_t expId = 455; // select experiment: 455
    // *********************************** //

    // File names and paths -----------------------------------------------------
    TString dir = gSystem->Getenv("VMCWORKDIR");
    TString filename, outputFilename, upexps_dir, ucesb_path, sofiacaldir;

    if (expId == 455)
    {
        // Input file
        filename = "s455_map_data_offline_20210515_194151.root";

        TString outputpath = "/path/to/your/disk/";
        // outputFilename = outputpath + "s455_cal_data_offline_" + oss.str() + ".root";
        outputFilename = "s455_cal_data_offline_" + oss.str() + ".root";

        sofiacaldir = dir + "/sofia/macros/s455Up2p/parameters/";
    }
    else
    {
        std::cout << "Experiment was not selected" << std::endl;
        gApplication->Terminate();
    }

    // store data or not ------------------------------------
    Bool_t fCal_level_califa = false;  // set true if there exists a file with the calibration parameters
    Bool_t NOTstoremappeddata = false; // if true, don't store mapped data in the root file
    Bool_t NOTstorecaldata = false;    // if true, don't store cal data in the root file
    Bool_t NOTstorehitdata = false;    // if true, don't store hit data in the root file

    // Setup: Selection of detectors ----------------------------------------------------
    // --- R3B standard -----------------------------------------------------------------
    Bool_t fNeuland = false; // NeuLAND for neutrons behind GLAD
    Bool_t fAms = false;     // AMS tracking detectors
    Bool_t fCalifa = false;  // Califa calorimeter
    Bool_t fMusic = false;   // R3B-Music: Ionization chamber for charge-Z
    // --- Sofia ------------------------------------------------------------------------
    Bool_t fMwpc0 = true;    // MWPC0 for tracking at entrance of Cave-C
    Bool_t fTrim = true;     // Triple-MUSIC for the HI beam charge-Z id, with charge-q states
    Bool_t fAt = false;      // Active Targer for Coulomb-induced fission
    Bool_t fSci = true;      // Start: Plastic scintillator for ToF
    Bool_t fMwpc1 = true;    // MWPC1 for tracking of fragments in front of target
    Bool_t fMwpc2 = true;    // MWPC2 for tracking of fragments before GLAD
    Bool_t fTwim = true;     // Twim: Ionization chamber for charge-Z of fragments
    Bool_t fMwpc3 = true;    // MWPC3 for tracking of fragments behind GLAD
    Bool_t fTofW = true;     // ToF-Wall for time-of-flight of fragments behind GLAD
    Bool_t fScalers = false; // SIS3820 scalers at Cave C
    // --- Traking ----------------------------------------------------------------------
    Bool_t fTracking = false; // Tracking of fragments inside GLAD and before GLAD

    // Calibration files for SOFIA ----------------------------------------------
    TString sofiacalfilename = sofiacaldir + "CalibParam.par";
    sofiacalfilename.ReplaceAll("//", "/");
    // Parameters for CALIFA mapping  -------------------------------------------
    TString califadir = dir + "/macros/r3b/unpack/s455/califa/parameters/";
    TString califamapfilename = califadir + "Califa_Mapping_3March2021.par";
    califamapfilename.ReplaceAll("//", "/");
    // Parameters for CALIFA calibration in keV  --------------------------------
    TString califacalfilename = califadir + "Califa_CalPar_4March2021.par";
    califacalfilename.ReplaceAll("//", "/");
    // Parameters for AMS   -----------------------------------------------------
    TString amscalfilename = sofiacaldir + "Ams_CalPar_20210312.par";
    amscalfilename.ReplaceAll("//", "/");

    // Create source using root files for input ---------------------------------
    FairRunAna* run = new FairRunAna();
    run->SetSink(new FairRootFileSink(outputFilename));

    // Runtime data base ------------------------------------
    FairRuntimeDb* rtdb = run->GetRuntimeDb();

    FairParAsciiFileIo* parIo1 = new FairParAsciiFileIo(); // Ascii
    TList* parList1 = new TList();
    parList1->Add(new TObjString(sofiacalfilename));
    if (fCalifa)
    {
        if (fCal_level_califa)
            parList1->Add(new TObjString(califacalfilename));
        else
            parList1->Add(new TObjString(califamapfilename));
    }
    if (fAms)
        parList1->Add(new TObjString(amscalfilename));
     rtdb->addRun(fRunId);
    parIo1->open(parList1);
    rtdb->setFirstInput(parIo1);
    rtdb->print();
    
  /*
  FairParRootFileIo* parIo1 = new FairParRootFileIo();
  //parIo1->open("Cal1.root","in");
  //rtdb->setFirstInput(parIo1);
  
      TList* parList1 = new TList();
    parList1->Add(new TObjString("Cal1.root"));
       // parList1->Add(new TObjString("Cal2.root"));
      parIo1->open(parList1);
    rtdb->setFirstInput(parIo1);
  
     rtdb->addRun(fRunId);
                    rtdb->getContainer("twimHitPar");
                    rtdb->setInputVersion(fRunId, (char*)"twimHitPar", 1, 1);

rtdb->initContainers(1);
   rtdb->addRun(2);
                    rtdb->getContainer("twimHitPar");
                    rtdb->setInputVersion(2, (char*)"twimHitPar", 1, 1);
                   rtdb->initContainers(2);
                    */
                   
    R3BFileSource* source = new R3BFileSource(filename);
    // source->SetInputFileName("./parameters/setup_runid.par");
    source->SetRunId(fRunId);
    run->SetSource(source);

    // Add RunId Reader  --------------------------------------------------------
    //R3BRunIdReader* RunIdTask = new R3BRunIdReader();
    //run->AddTask(RunIdTask);

    // Add analysis task --------------------------------------------------------
    // MWPC0
    if (fMwpc0)
    {
        R3BSofMwpc0Mapped2Cal* MW0Map2Cal = new R3BSofMwpc0Mapped2Cal();
        MW0Map2Cal->SetOnline(NOTstorecaldata);
        run->AddTask(MW0Map2Cal);

        R3BSofMwpc0Cal2Hit* MW0Cal2Hit = new R3BSofMwpc0Cal2Hit();
        MW0Cal2Hit->SetOnline(NOTstorehitdata);
        run->AddTask(MW0Cal2Hit);
    }

    // SCI
    if (fSci)
    {
        // --- Mapped 2 Tcal for SofSci
        R3BSofSciMapped2Tcal* SofSciMap2Tcal = new R3BSofSciMapped2Tcal();
        SofSciMap2Tcal->SetOnline(NOTstorecaldata);
        run->AddTask(SofSciMap2Tcal);

        // --- Tcal 2 SingleTcal for SofSci
        R3BSofSciTcal2SingleTcal* SofSciTcal2STcal = new R3BSofSciTcal2SingleTcal();
        SofSciTcal2STcal->SetOnline(NOTstorecaldata);
        run->AddTask(SofSciTcal2STcal);

        // --- SingleTcal 2 Cal for SofSci
        R3BSofSciSingleTcal2Cal* SofSciSTcal2Cal = new R3BSofSciSingleTcal2Cal();
        SofSciSTcal2Cal->SetOnline(NOTstorecaldata);
        run->AddTask(SofSciSTcal2Cal);

        // --- SingleTcal 2 Hit for SofSci
        R3BSofSciSingleTcal2Hit* SofSciSTcal2Hit = new R3BSofSciSingleTcal2Hit();
        SofSciSTcal2Hit->SetOnline(NOTstorehitdata);
        SofSciSTcal2Hit->SetCalParams(675., -1922.); // ToF calibration at Cave-C
        run->AddTask(SofSciSTcal2Hit);
    }

    // Triple-MUSIC
    if (fTrim)
    {
        // --- Mapped 2 Cal
        R3BSofTrimMapped2Cal* SofTrimMap2Cal = new R3BSofTrimMapped2Cal();
        SofTrimMap2Cal->SetOnline(NOTstorecaldata);
        run->AddTask(SofTrimMap2Cal);

        // --- Cal 2 Hit
        R3BSofTrimCal2Hit* SofTrimCal2Hit = new R3BSofTrimCal2Hit();
        SofTrimCal2Hit->SetOnline(NOTstorehitdata);
        SofTrimCal2Hit->SetExpId(expId);
        SofTrimCal2Hit->SetCoulex(kFALSE);
        SofTrimCal2Hit->SetTriShape(kTRUE);
        run->AddTask(SofTrimCal2Hit);
    }

    // AMS
    if (fAms)
    {
        R3BAmsMapped2StripCal* AmsMap2Cal = new R3BAmsMapped2StripCal();
        AmsMap2Cal->SetOnline(NOTstorecaldata);
        run->AddTask(AmsMap2Cal);
        R3BAmsStripCal2Hit* AmsCal2Hit = new R3BAmsStripCal2Hit();
        AmsCal2Hit->SetOnline(NOTstorehitdata);
        run->AddTask(AmsCal2Hit);
    }

    // CALIFA
    if (fCalifa && fCal_level_califa)
    {
        // R3BCalifaMapped2CrystalCal ---
        R3BCalifaMapped2CrystalCal* CalifaMap2Cal = new R3BCalifaMapped2CrystalCal();
        CalifaMap2Cal->SetOnline(NOTstorecaldata);
        run->AddTask(CalifaMap2Cal);
        // R3BCalifaCrystalCal2Hit ---
        R3BCalifaCrystalCal2Hit* CalifaCal2Hit = new R3BCalifaCrystalCal2Hit();
        CalifaCal2Hit->SetCrystalThreshold(350.); // 100keV
        CalifaCal2Hit->SetDRThreshold(20000.);    // 10MeV
        CalifaCal2Hit->SelectGeometryVersion(2021);
        CalifaCal2Hit->SetOnline(NOTstorehitdata);
        run->AddTask(CalifaCal2Hit);
    }

    // MWPC1
    if (fMwpc1)
    {
        R3BSofMwpc1Mapped2Cal* MW1Map2Cal = new R3BSofMwpc1Mapped2Cal();
        MW1Map2Cal->SetOnline(NOTstorecaldata);
        run->AddTask(MW1Map2Cal);

        R3BSofMwpc1Cal2Hit* MW1Cal2Hit = new R3BSofMwpc1Cal2Hit();
        MW1Cal2Hit->SetOnline(NOTstorehitdata);
        run->AddTask(MW1Cal2Hit);
    }

    // MWPC2
    if (fMwpc2)
    {
        R3BSofMwpc2Mapped2Cal* MW2Map2Cal = new R3BSofMwpc2Mapped2Cal();
        MW2Map2Cal->SetOnline(NOTstorecaldata);
        run->AddTask(MW2Map2Cal);

        R3BSofMwpc2Cal2Hit* MW2Cal2Hit = new R3BSofMwpc2Cal2Hit();
        MW2Cal2Hit->SetOnline(NOTstorehitdata);
        run->AddTask(MW2Cal2Hit);
    }

    // MWPC3
    if (fMwpc3)
    {
        R3BSofMwpc3Mapped2Cal* MW3Map2Cal = new R3BSofMwpc3Mapped2Cal();
        MW3Map2Cal->SetOnline(NOTstorecaldata);
        run->AddTask(MW3Map2Cal);

        R3BSofMwpc3Cal2Hit* MW3Cal2Hit = new R3BSofMwpc3Cal2Hit();
        MW3Cal2Hit->SetOnline(NOTstorehitdata);
        run->AddTask(MW3Cal2Hit);
    }

    // ToF-Wall
    if (fTofW)
    {
        // --- Mapped 2 Tcal for SofTofW
        R3BSofTofWMapped2Tcal* SofTofWMap2Tcal = new R3BSofTofWMapped2Tcal();
        SofTofWMap2Tcal->SetOnline(NOTstorecaldata);
        run->AddTask(SofTofWMap2Tcal);

        // --- Tcal 2 SingleTcal for SofTofW
        R3BSofTofWTcal2SingleTcal* SofTofWTcal2STcal = new R3BSofTofWTcal2SingleTcal();
        SofTofWTcal2STcal->SetOnline(NOTstorecaldata);
        run->AddTask(SofTofWTcal2STcal);

        // --- SingleTcal 2 Hit for SofTofW
        R3BSofTofWSingleTCal2Hit* SofTofWSingleTcal2Hit = new R3BSofTofWSingleTCal2Hit();
        SofTofWSingleTcal2Hit->SetOnline(NOTstorehitdata);
        SofTofWSingleTcal2Hit->SetExpId(expId);
        SofTofWSingleTcal2Hit->SetTofLISE(33.);
        run->AddTask(SofTofWSingleTcal2Hit);
    }

    // TWIM
    if (fTwim)
    {
        R3BSofTwimMapped2Cal* TwimMap2Cal = new R3BSofTwimMapped2Cal();
        TwimMap2Cal->SetOnline(NOTstorecaldata);
        TwimMap2Cal->SetExpId(expId);
        run->AddTask(TwimMap2Cal);

        R3BSofTwimCal2Hit* TwimCal2Hit = new R3BSofTwimCal2Hit();
        TwimCal2Hit->SetOnline(NOTstorehitdata);
        run->AddTask(TwimCal2Hit);
    }

    // Initialize -------------------------------------------
    run->Init();
    FairLogger::GetLogger()->SetLogScreenLevel("INFO");
  /*
  Bool_t kParameterMerged = kTRUE;
  FairParRootFileIo* parOut = new FairParRootFileIo(kParameterMerged);
  parOut->open("Cal1.root");
  rtdb->setOutput(parOut);
*/
    // Run --------------------------------------------------
    if (nev > -1)
        run->Run(nev);
    else
        run->Run();    
        
    // Save parameters (if needed) --------------------------
    //rtdb->saveOutput();     

    // Finish -----------------------------------------------
    timer.Stop();
    Double_t rtime = timer.RealTime();
    Double_t ctime = timer.CpuTime();
    std::cout << std::endl << std::endl;
    std::cout << "Macro finished succesfully." << std::endl;
    std::cout << "Output file is " << outputFilename << std::endl;
    std::cout << "Real time " << rtime << " s, CPU time " << ctime << " s" << std::endl << std::endl;
    gApplication->Terminate();
}
