name: static analysis
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

permissions: write-all

jobs:
  # This workflow contains a single job called "clang-format"
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Code formatting
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt-get update
          sudo apt-get install clang-format-15
          ./.clang-format-check.sh clang-format-15
        shell: bash
