##############################################################################
#   Copyright (C) 2019 GSI Helmholtzzentrum für Schwerionenforschung GmbH    #
#   Copyright (C) 2019 University of Santiago de Compostela                  #
#   Copyright (C) 2019 CEA-DAM-DIF, Université Paris-Saclay                  #
#   Copyright (C) 2023 University of Coruña                                  #
#   Copyright (C) 2019-2025 Members of R3B Collaboration                     #
#                                                                            #
#             This software is distributed under the terms of the            #
#                 GNU General Public Licence (GPL) version 3,                #
#                    copied verbatim in the file "LICENSE".                  #
#                                                                            #
# In applying this license GSI does not waive the privileges and immunities  #
# granted to it by virtue of its status as an Intergovernmental Organization #
# or submit itself to any jurisdiction.                                      #
##############################################################################

# This is the main static analysis workflow for pull requests to the sofia dev branch
# See the static analysis workflow developed for R3BRoot for more details
# SPDX-License-Identifier: LGPL-3.0-or-later

name: static analysis
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

permissions: write-all

jobs:
  # This workflow contains a single job called "clang-format"
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Code formatting
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt-get update
          sudo apt-get install clang-format-15
          ./.clang-format-check.sh clang-format-15
        shell: bash
